development:
  adapter: postgresql
  encoding: utf8
  database: beerica_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: beerica_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: beerica_production
  pool: 5
  timeout: 5000
